apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    env: prod
spec:
  selector:
    matchLabels:
      env: prod
  replicas: 3
  template:
    metadata:
      name: nginx 
      labels:
        env: prod
    spec:
      containers:
        - name: nginx
          image: nginx

